<?php echo $this->doctype() . "\n"; ?>
<html>
  <head>

    <link href="<?= $this->baseUrl() ?>/css/jquery-ui-1.8.18.custom.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/css/global.css" rel="stylesheet">


    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery.min.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui-1.8.18.custom.min.js"></script>

    <?php $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.datatable.js"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.dataTables.columnFilter.js"); ?>

    <?php $this->headScript()->appendFile($this->baseUrl() . "/bootstrap/js/bootstrap.js"); ?>

    <?php $this->headScript()->appendFile($this->baseUrl() . "/js/my.js"); ?>

    <?php echo $this->partial('partials/headmeta.phtml'); ?>


    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>

  </head>
  <body>
    <div class="container">
      <?= $this->navigation()->menu()->setPartial("partials/menu.phtml"); ?>

      <?php echo $this->partial('partials/brandsocial.phtml'); ?>

      <div id="main" class="well">

        <?php echo $this->navigation()->breadcrumbs()->setPartial("partials/breadcrumb.phtml"); ?>
        <?php echo $this->layout()->content; ?>

      </div>
      <div id="footer" class="well">
        
      </div>

    </div>

    <?php echo $this->inlineScript(); ?>
  </body>
</html>