<?php echo $this->doctype() . "\n"; ?>
<html>
  <head>

    <link href="<?= $this->baseUrl() ?>/css/jquery-ui-1.8.18.custom.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="<?= $this->baseUrl() ?>/css/global.css" rel="stylesheet">


    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery.min.js"></script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui-1.8.18.custom.min.js"></script>

    <?php $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.datatable.js"); ?>
    <?php $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.dataTables.columnFilter.js"); ?>

    <?php $this->headScript()->appendFile($this->baseUrl() . "/bootstrap/js/bootstrap.js"); ?>

    <?php $this->headScript()->appendFile($this->baseUrl() . "/js/general.js"); ?>


    <?php
    echo $this->headTitle('ZFStart')
            ->setSeparator(' | ')
    ;
    ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>

  </head>
  <body>


    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        
        <div class="container">
          <a class="brand" href="<?php echo $this->baseUrl(); ?>">
            <span style="color:#CE2D1B">ZF</span><span style="color: #333 ">Start</span>
          </a>
          <?php echo $this->navigation()->menu()->setPartial("partials/menu.phtml"); ?>
        </div><!-- eo navbar container -->
      </div><!-- eo navbar inner -->
    </div><!-- eo navbar -->




    <br>
    <br>

    <div class="container">

      <div id="header" class="well">
        <a href="<?= $this->baseUrl(); ?>"><h1>ZF Start</h1></a>
        <h3>Leer klappen en babbelen</h3>
      </div>


      <div id="main" class="well">
        <?php echo $this->navigation()->breadcrumbs()->setPartial("partials/breadcrumb.phtml"); ?>
        <img class="pull-right" src="<?php echo $this->baseUrl() ?>/images/skype.png"/>
        <?php echo $this->layout()->content; ?>

      </div>
      
      <div id="footer" class="well">
        
      </div>
      
        




    </div>






    <?php echo $this->inlineScript(); ?>
  </body>
</html>