<ul>
  <li id="categories"><h3>Categories</h3>
    <ul>
      <li><a title="View all posts filed under 4×4 Vehicles" href="http://memela.co.za/blog/category/bush-attractions-activities/4x4-vehicles/">4×4 Vehicles</a></li>
      <li><a title="View all posts filed under Beach &amp; Ocean Attractions" href="http://memela.co.za/blog/category/beach-ocean-attractions/">Beach &amp; Ocean Attractions</a></li>
      <li><a title="View all posts filed under Booking or Inquiry" href="http://memela.co.za/blog/category/booking-or-inquiry/">Booking or Inquiry</a></li>
      <li><a title="View all posts filed under Bush Attractions &amp; Activities" href="http://memela.co.za/blog/category/bush-attractions-activities/">Bush Attractions &amp; Activities</a></li>
      <li><a title="Rustic catered accommodation in Kosi Bay" href="http://memela.co.za/blog/category/memela-bush-camp/bush-camp-facilities/">Bush Camp Facilities</a></li>
      <li><a title="View all posts filed under Canoeing" href="http://memela.co.za/blog/category/bush-attractions-activities/canoeing/">Canoeing</a></li>
      <li><a title="View all posts filed under Cultural Activities" href="http://memela.co.za/blog/category/bush-attractions-activities/cultural-activities/">Cultural Activities</a></li>
      <li><a title="View all posts filed under Dolphin Encounters" href="http://memela.co.za/blog/category/beach-ocean-attractions/dolphin-encounters/">Dolphin Encounters</a></li>
      <li><a title="View all posts filed under Isimangaliso" href="http://memela.co.za/blog/category/conservation/isimangaliso/">Isimangaliso</a></li>
      <li><a title="View all posts filed under Kosi Activity Excursions Prices" href="http://memela.co.za/blog/category/kosi-activity-prices/">Kosi Activity Excursions Prices</a></li>
      <li><a title="Kosi Bay Adventure Attractions &amp; Activities" href="http://memela.co.za/blog/category/kosi-bay-adventure-attractions-activities/">Kosi Bay Adventure Attractions &amp; Activities</a></li>
      <li><a title="View all posts filed under Kosi Bay Nature" href="http://memela.co.za/blog/category/conservation/kosi-bay-nature/">Kosi Bay Nature</a></li>
      <li><a title="View all posts filed under Kosi Birding" href="http://memela.co.za/blog/category/bush-attractions-activities/kosi-birding/">Kosi Birding</a></li>
      <li><a title="View all posts filed under Kosi Hiking and trails" href="http://memela.co.za/blog/category/bush-attractions-activities/kosi-hiking-and-trails/">Kosi Hiking and trails</a></li>
      <li><a title="View all posts filed under Kosi Lakes" href="http://memela.co.za/blog/category/bush-attractions-activities/kosi-lakes/">Kosi Lakes</a></li>
      <li><a title="View all posts filed under Kosi Mouth" href="http://memela.co.za/blog/category/beach-ocean-attractions/kosi-mouth/">Kosi Mouth</a></li>
      <li><a title="View all posts filed under Kosi Photo Gallery" href="http://memela.co.za/blog/category/kosi-photo-gallery/">Kosi Photo Gallery</a></li>
      <li><a title="View all posts filed under Manguzi" href="http://memela.co.za/blog/category/maputaland/manguzi/">Manguzi</a></li>
      <li><a title="View all posts filed under Map and directions" href="http://memela.co.za/blog/category/maputaland/map-and-directions/">Map and directions</a></li>
      <li><a title="View all posts filed under Maputaland" href="http://memela.co.za/blog/category/maputaland/">Maputaland</a></li>
      <li><a title="View all posts filed under Maputaland History" href="http://memela.co.za/blog/category/maputaland/maputaland-history/">Maputaland History</a></li>
      <li><a title="View all posts filed under Marine Protected Area" href="http://memela.co.za/blog/category/conservation/marine-protected-area/">Marine Protected Area</a></li>
      <li><a title="A small intimate bush camp in Kosi Bay, Maputaland, with wonderful hosts and excellent food." href="http://memela.co.za/blog/category/memela-bush-camp/">Memela Bush Camp</a></li>
      <li><a title="Bush Camp Accommodation, telephone, email contact details in Kosi Bay, Maputaland. Isimangaliso. Manguzi" href="http://memela.co.za/blog/category/memela-bush-camp/memela-bush-camp-contact-details/">Memela Bush Camp Contact Details</a></li>
      <li><a title="View all posts filed under Memela Bush Camp Staff" href="http://memela.co.za/blog/category/memela-bush-camp/memela-bush-camp-staff/">Memela Bush Camp Staff</a></li>
      <li><a title="Photos of Memela Bush Camp" href="http://memela.co.za/blog/category/memela-bush-camp/memela-bush-camp-photos/">More Memela Bush Camp Photos</a></li>
      <li><a title="View all posts filed under Mozambique, Ponta do Ouro" href="http://memela.co.za/blog/category/maputaland/mozambique-ponta-do-ouro/">Mozambique, Ponta do Ouro</a></li>
      <li><a title="View all posts filed under Nature &amp; Conservation" href="http://memela.co.za/blog/category/conservation/">Nature &amp; Conservation</a></li>
      <li><a title="View all posts filed under Ocean Experience" href="http://memela.co.za/blog/category/beach-ocean-attractions/ocean-experience/">Ocean Experience</a></li>
      <li><a title="View all posts filed under Permits Needed" href="http://memela.co.za/blog/category/conservation/permits-needed/">Permits Needed</a></li>
      <li><a title="View all posts filed under Ramsar" href="http://memela.co.za/blog/category/conservation/ramsar/">Ramsar</a></li>
      <li><a title="View all posts filed under Scuba and diving" href="http://memela.co.za/blog/category/beach-ocean-attractions/scuba-and-diving/">Scuba and diving</a></li>
      <li><a title="View all posts filed under Tembe Elephant Park" href="http://memela.co.za/blog/category/bush-attractions-activities/tembe-elephant-park/">Tembe Elephant Park</a></li>
      <li><a title="View all posts filed under Thonga Culture" href="http://memela.co.za/blog/category/maputaland/thonga-culture/">Thonga Culture</a></li>
      <li><a title="View all posts filed under Turtles" href="http://memela.co.za/blog/category/beach-ocean-attractions/turtles/">Turtles</a></li>
      <li><a title="View all posts filed under UNESCO" href="http://memela.co.za/blog/category/conservation/unesco/">UNESCO</a></li>
      <li><a title="View all posts filed under Whale Watching" href="http://memela.co.za/blog/category/beach-ocean-attractions/whale-watching/">Whale Watching</a></li>
    </ul>
  </li>
  <li id="archives"><h3>Archives</h3>
    <ul>
      <li><a title="September 2011" href="http://memela.co.za/blog/2011/09/">September 2011</a></li>
      <li><a title="August 2011" href="http://memela.co.za/blog/2011/08/">August 2011</a></li>
      <li><a title="July 2011" href="http://memela.co.za/blog/2011/07/">July 2011</a></li>
      <li><a title="June 2011" href="http://memela.co.za/blog/2011/06/">June 2011</a></li>
      <li><a title="February 2011" href="http://memela.co.za/blog/2011/02/">February 2011</a></li>
      <li><a title="January 2011" href="http://memela.co.za/blog/2011/01/">January 2011</a></li>
      <li><a title="December 2010" href="http://memela.co.za/blog/2010/12/">December 2010</a></li>
      <li><a title="November 2010" href="http://memela.co.za/blog/2010/11/">November 2010</a></li>
    </ul>
  </li>
  <li id="pages"><h3 class="widget-title">Pages</h3>
    <ul>
      <li class="page_item page-item-2"><a href="http://memela.co.za/blog/bookings/">Booking &amp; Inquiries</a></li>
      <li><a href="http://memela.co.za/blog/contact-details/">Contact Details</a></li>
      <li><a href="http://memela.co.za/blog/facility-rates/">Facility &amp; Rates</a></li>
      <li><a href="http://memela.co.za/blog/guest-comments/">Guest Comments</a></li>
      <li><a href="http://memela.co.za/blog/map-directions/">Map &amp; Directions</a></li>
      <li><a href="http://memela.co.za/blog/memela-bush-camp-photos/">Photo Gallery</a></li>
    </ul>
  </li>
  <li id="links"><h3 class="widget-title">Tourism Info</h3>
    <ul>
      <li><a title="Kosi Bay Tourism and Accommodation Info" href="http://www.kositourism.co.za">Kosi Tourism</a></li>
      <li><a title="A good site for more tourism information." href="http://www.maputaland.net">Maputaland Tourism Info</a></li>
    </ul>
  </li>
</ul>