<div class="brand" >
  <?php echo $this->partial('partials/social.phtml'); ?>
  <img src="<?php echo $this->baseUrl() ?>/images/logo.jpg" width="120px"/>
  <div class="pull-right">
    <h1>
      <a href="<?= $this->baseUrl() ;?>"><span style="color:#0088CC"><?= $this->translate('site_name') ;?></span></a>
    </h1>
    <h4>Kjlkjlkjlkjlkj | <?= $this->translate('lkjlkjlkjlkjlkjlk'); ?> - N. Calif </h4>
  </div>
</div>
