<div class="brand" >
  <img src="<?php echo $this->baseUrl() ?>/images/memela-logo.jpg" width="120px"/>
  <div class="pull-right">
    <h1>
      <a href="<?php echo $this->baseUrl(); ?>">
        <span style="color:#0088CC">Memela Bush</span>
        <span style="color: #333 ">Lodge</span>
      </a>
    </h1>
    <h4>Kosi Bay Accommodation | <?= $this->translate('simple_authentic'); ?> - N. Calif </h4>
  </div>
</div>
