<ul class="breadcrumb2">
  <li>
    <a href="<?php echo $this->baseUrl() ?>"><?= $this->translate('home'); ?></a> 
  </li>
  <?php
  foreach ($this->pages as $page) {
    ?><li><?php
  if ($page->isActive()) {
      ?>
        <span class='divider'> | </span>&nbsp<?= $this->translate($page->getLabel()); ?>
        <?php
      } else {
        ?>
        <span class='divider'> | </span><a href='<?php echo $this->baseUrl() ?>/<?php echo $page->getController() ?>/<?= $this->translate($page->getLabel()) ?></a>
        <?php
      }
      ?></li><?php
  }
    ?>
</ul>
