
<ul class="breadcrumb2">
  <li>
    <a href="<?php echo $this->baseUrl() ?>"><?= $this->translate('home'); ?></a> 
  </li>
  <?php
  foreach ($this->pages as $page) {
    ?><li><?php
  if ($page->isActive()) {
      ?>
        <span class='divider'> | </span>&nbsp<?= $this->translate($page->getLabel()); ?>
        <?php
      } else {
        ?>
        <a href='
           <?php echo $this->baseUrl() ?>/
           <?php echo $page->getController() ?>/
           <?php echo $page->getAction() ?>'>
          <span class='divider'> | </span><?= $this->translate($page->getLabel()) ?>
        </a>
        <?php
      }
      ?></li><?php
  }
    ?>
</ul>