<div class="navbar">
        <div class="navbar-inner">
      
<div class="nav-collapse">
  <ul class="nav">
    <?php
    foreach ($this->container->getPages() AS $page) {

      $haveSubPages = ($page->count() != 0) ? true : false;

      if ($page->isVisible()) {
        if ($haveSubPages) {
          ?>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate($page->getLabel()) ?><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php
            } else {
              ?>
              <li><a href="<?php echo $this->baseUrl() . "/" . $page->getController() . "/" . $page->getAction(); ?>"><?php echo $this->translate($page->getLabel()) ?></a>
                <?php
              }
              foreach ($page->getPages() AS $subPage) {
                // ------------------------------------------

                $haveSubSubPages = ($subPage->count() != 0) ? true : false;

                if ($subPage->isVisible()) {
                  if ($haveSubSubPages) {
                    ?>
                  <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate($subPage->getLabel()) ?><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <?php
                    } else {
                      ?>
                      <li><a href="<?php echo $this->baseUrl() . "/" . $subPage->getController() . "/" . $subPage->getAction(); ?>" ><?php echo $this->translate($subPage->getLabel()) ?></a>
                        <?php
                      }
                      foreach ($subPage->getPages() AS $subsubPage) {
                        if ($subsubPage->isVisible()) {
                          ?><li><a href="<?php echo $this->baseUrl() . "/" . $subsubPage->getController() . "/" . $subsubPage->getAction(); ?>"><?php echo $this->translate($subsubPage->getLabel()) ?></a></li><?php
            }
          }
          if ($haveSubSubPages) {
                        ?></ul><?php
          }
                      ?></li><?php
          }

          // ------------------------------------------ 
        }
        if ($haveSubPages) {
                    ?></ul><?php
        }
                  ?></li><?php
      }
    }
              ?>
  </ul>

</div>
     </div><!-- eo navbar inner -->
      </div><!-- eo navbar -->